### ISSUE TITLE
Pushwoosh notification do not get when Android app is not running.

### ISSUE THREAD

**Issue by alexakasanjeev** [Pushwoosh/pushwoosh-android-sdk#120]
Only on some certain Android devices, notification is only triggered when instance of app is on Foreground or background. Please help

**Comment by wfhm** [comment]
@alexakasanjeev Hi,

Our support team has informed us that you have also created a support ticket regarding this issue which is already solved (the issue was with a power-saving mode). Could you please confirm it, or, if the issue persists, provide us with a bit more details on Android OS versions and device models?

**Comment by wfhm** [comment]
@alexakasanjeev could you please confirm that your issue was resolved via Support channel?

**Comment by alexakasanjeev** [comment]
The issue was partially resolved, some devices come with a configuration that is out of the scope
